# -*- coding: utf-8 -*-
"""ixtiyoriy dastur.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hC5CeehzdwD80cumOSFJD8uwHOG6zDQw
"""

son1 = float(input("Birinchi sonni kiriting: "))
son2 = float(input("Ikkinchi sonni kiriting: "))


yigindi = son1 + son2
ayirma = son1 - son2
kopaytma = son1 * son2
if son2 != 0:
    bolinma = son1 / son2
else:
    bolinma = "Bo'linmaydi (0 ga bo'lish mumkin emas)"


print("\nNatijalar:")
print(f"Yig'indisi: {yigindi}")
print(f"Ayirma: {ayirma}")
print(f"Ko'paytma: {kopaytma}")
print(f"Bo'linma: {bolinma}")